sudo: false 

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  # - "3.5"
  # - "nightly"

install: "pip install -e ."

script: py.test

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: "3.4"

after_success:
  - coveralls